In [1]:
# We can see in this python notebook how to implement KNN algorithm FOR CLASSIFICATION

In [2]:
#Downloading important libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Assigning the CSV data into a Variable
dataset=pd.read_csv("Social_Network_Ads.csv")

In [4]:
#Displaying the value exists in the variable
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
# AI algorithms can not handle categorical data, since "Gender" column contains 
# categorical values we need to convert the categorical value into numerical values
# using below method.

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True) # here drop_first = True depicts that deleting the first distinct value of the gender column while converting to numerical value columns

In [7]:
dataset #Post conversion display the value

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [8]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [9]:
# In the dataset user id column is of no use, hence we can delete the user id column using below method
dataset=dataset.drop("User ID",axis=1) #axis = 1 says that, the processor will search for "User ID" column wise.

In [10]:
dataset #Print and verify that the user id column has been deleted

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [11]:
#separate the independent and dependent columns
independent=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]

In [12]:
independent

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [13]:
dependent=dataset[['Purchased']]

In [14]:
dependent

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [15]:
independent.shape # to display the no of rows and columns

(400, 3)

In [16]:
dependent.shape # to display the no of rows and columns

(400, 1)

In [17]:
dependent['Purchased'].value_counts() # To display the distinct values along with its count in the dataset
# As per this output we can confirm that the dataset is imbalanced dataset as 
# for 0 the count is 257 and for 1 the count is 143

0    257
1    143
Name: Purchased, dtype: int64

In [18]:
#Splitting the training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size = 0.30, random_state = 0)


In [19]:
# From here the coding starts specific with "CLASSIFICATION"
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2)
classifier.fit(X_train,Y_train)  # CLASSIFICATION model creation

C:\Users\krish\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [20]:
Y_pred=classifier.predict(X_test) #For the test set of input, predict the output and store in Y_pred

In [21]:
# In CLASSIFICATION the evaluation metrics is based on "CONFUSION MATRIX"
# Not based on R score . Please note.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred) # Evaluation means war between actual and predicted output.

In [22]:
print(cm) # to display the value for cm Evaluation metrics
# the below output overall sum matches the test data count

[[72  7]
 [13 28]]


In [23]:
#To compute the CONFUSION MATRIX in a report format

from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,Y_pred) # war between actual and prediction

In [24]:
# To print the CONFUSION MATRIX in a CLASSIFICATION report format

print(clf_report)

              precision    recall  f1-score   support

           0       0.85      0.91      0.88        79
           1       0.80      0.68      0.74        41

    accuracy                           0.83       120
   macro avg       0.82      0.80      0.81       120
weighted avg       0.83      0.83      0.83       120



## print(cm)

In [25]:
age_input=float(input("Age: "))
salary_input=float(input("Salary: "))
gender_male_input=int(input("Gender: 0 or 1 : "))

Age: 23
Salary: 2000000
Gender: 0 or 1 : 1


In [26]:
classifier.predict([[age_input,salary_input,gender_male_input]])

array([1], dtype=int64)

In [35]:
################# Trying with Different Playable Parameters ######################
# From here the coding starts specific with "CLASSIFICATION"
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2, weights='uniform', algorithm='auto')
#classifier = KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2, weights='uniform', algorithm='ball_tree')
#classifier = KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2, weights='uniform', algorithm='kd_tree')
#classifier = KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2, weights='uniform', algorithm='brute')

#classifier = KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2, weights='distance', algorithm='auto')
#classifier = KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2, weights='distance', algorithm='ball_tree')
#classifier = KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2, weights='distance', algorithm='kd_tree')
#classifier = KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2, weights='distance', algorithm='brute')

classifier.fit(X_train,Y_train)  # CLASSIFICATION model creation


Y_pred=classifier.predict(X_test) #For the test set of input, predict the output and store in Y_pred
# In CLASSIFICATION the evaluation metrics is based on "CONFUSION MATRIX"
# Not based on R score . Please note.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred) # Evaluation means war between actual and predicted output.
print(cm) # to display the value for cm Evaluation metrics
# the below output overall sum matches the test data count


#To compute the CONFUSION MATRIX in a report format

from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,Y_pred) # war between actual and prediction

# To print the CONFUSION MATRIX in a report format

print(clf_report)

[[72  7]
 [13 28]]
              precision    recall  f1-score   support

           0       0.85      0.91      0.88        79
           1       0.80      0.68      0.74        41

    accuracy                           0.83       120
   macro avg       0.82      0.80      0.81       120
weighted avg       0.83      0.83      0.83       120



C:\Users\krish\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  from ipykernel import kernelapp as app
