In [1]:
# We can see in this python notebook how to implement NaviesBayes algorithm FOR CLASSIFICATION

In [2]:
#Downloading important libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Assigning the CSV data into a Variable
dataset=pd.read_csv("Social_Network_Ads.csv")

In [4]:
#Displaying the value exists in the variable
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
# AI algorithms can not handle categorical data, since "Gender" column contains 
# categorical values we need to convert the categorical value into numerical values
# using below method.

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True) # here drop_first = True depicts that deleting the first distinct value of the gender column while converting to numerical value columns

In [7]:
dataset #Post conversion display the value

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [8]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [9]:
# In the dataset user id column is of no use, hence we can delete the user id column using below method
dataset=dataset.drop("User ID",axis=1)

In [10]:
dataset #Print and verify that the user id column has been deleted

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [11]:
#separate the independent and dependent columns
independent=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]

In [12]:
independent

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [13]:
dependent=dataset[['Purchased']]

In [14]:
dependent

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [15]:
independent.shape # to display the no of rows and columns

(400, 3)

In [16]:
dependent.shape # to display the no of rows and columns

(400, 1)

In [17]:
dependent['Purchased'].value_counts() # To display the distinct values along with its count in the dataset
# As per this output we can confirm that the dataset is imbalanced dataset as 
# for 0 the count is 257 and for 1 the count is 143

0    257
1    143
Name: Purchased, dtype: int64

In [18]:
#Splitting the training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(independent, dependent, test_size = 0.30, random_state = 0)


In [20]:
# From here the coding starts specific with "CLASSIFICATION"
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,Y_train)  # CLASSIFICATION model creation

C:\Users\krish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [21]:
Y_pred=classifier.predict(X_test) #For the test set of input, predict the output and store in Y_pred

In [22]:
# In CLASSIFICATION the evaluation metrics is based on "CONFUSION MATRIX"
# Not based on R score . Please note.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred) # Evaluation means war between actual and predicted output.

In [23]:
print(cm) # to display the value for cm Evaluation metrics
# the below output overall sum matches the test data count

[[74  5]
 [ 8 33]]


In [24]:
#To compute the CONFUSION MATRIX in a report format

from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,Y_pred) # war between actual and prediction

In [25]:
# To print the CONFUSION MATRIX in a report format

print(clf_report)

              precision    recall  f1-score   support

           0       0.90      0.94      0.92        79
           1       0.87      0.80      0.84        41

    accuracy                           0.89       120
   macro avg       0.89      0.87      0.88       120
weighted avg       0.89      0.89      0.89       120



## print(cm)

In [26]:
age_input=float(input("Age: "))
salary_input=float(input("Salary: "))
gender_male_input=int(input("Gender: 0 or 1 : "))

Age: 23
Salary: 2000000
Gender: 0 or 1 : 1


In [27]:
classifier.predict([[age_input,salary_input,gender_male_input]])

array([1], dtype=int64)

In [28]:
########### MultinomialNB() ####################

In [30]:
# From here the coding starts specific with "CLASSIFICATION"
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train,Y_train)  # CLASSIFICATION model creation

C:\Users\krish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [31]:
Y_pred=classifier.predict(X_test) #For the test set of input, predict the output and store in Y_pred
# In CLASSIFICATION the evaluation metrics is based on "CONFUSION MATRIX"
# Not based on R score . Please note.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred) # Evaluation means war between actual and predicted output.
print(cm) # to display the value for cm Evaluation metrics
# the below output overall sum matches the test data count


#To compute the CONFUSION MATRIX in a report format

from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,Y_pred) # war between actual and prediction

# To print the CONFUSION MATRIX in a report format

print(clf_report)


[[68 11]
 [28 13]]
              precision    recall  f1-score   support

           0       0.71      0.86      0.78        79
           1       0.54      0.32      0.40        41

    accuracy                           0.68       120
   macro avg       0.62      0.59      0.59       120
weighted avg       0.65      0.68      0.65       120



In [32]:
########### BernoulliNB() ####################

# From here the coding starts specific with "CLASSIFICATION"
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train,Y_train)  # CLASSIFICATION model creation

Y_pred=classifier.predict(X_test) #For the test set of input, predict the output and store in Y_pred
# In CLASSIFICATION the evaluation metrics is based on "CONFUSION MATRIX"
# Not based on R score . Please note.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred) # Evaluation means war between actual and predicted output.
print(cm) # to display the value for cm Evaluation metrics
# the below output overall sum matches the test data count


#To compute the CONFUSION MATRIX in a report format

from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,Y_pred) # war between actual and prediction

# To print the CONFUSION MATRIX in a report format

print(clf_report)





[[79  0]
 [41  0]]
              precision    recall  f1-score   support

           0       0.66      1.00      0.79        79
           1       0.00      0.00      0.00        41

    accuracy                           0.66       120
   macro avg       0.33      0.50      0.40       120
weighted avg       0.43      0.66      0.52       120



C:\Users\krish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\krish\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [33]:
########### CategoricalNB() ####################

# From here the coding starts specific with "CLASSIFICATION"
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB()
classifier.fit(X_train,Y_train)  # CLASSIFICATION model creation

Y_pred=classifier.predict(X_test) #For the test set of input, predict the output and store in Y_pred
# In CLASSIFICATION the evaluation metrics is based on "CONFUSION MATRIX"
# Not based on R score . Please note.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred) # Evaluation means war between actual and predicted output.
print(cm) # to display the value for cm Evaluation metrics
# the below output overall sum matches the test data count


#To compute the CONFUSION MATRIX in a report format

from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,Y_pred) # war between actual and prediction

# To print the CONFUSION MATRIX in a report format

print(clf_report)

ImportError: cannot import name 'CategoricalNB' from 'sklearn.naive_bayes' (C:\Users\krish\Anaconda3\lib\site-packages\sklearn\naive_bayes.py)

In [34]:
########### ComplementNB() ####################

# From here the coding starts specific with "CLASSIFICATION"
from sklearn.naive_bayes import ComplementNB
classifier = ComplementNB()
classifier.fit(X_train,Y_train)  # CLASSIFICATION model creation

Y_pred=classifier.predict(X_test) #For the test set of input, predict the output and store in Y_pred
# In CLASSIFICATION the evaluation metrics is based on "CONFUSION MATRIX"
# Not based on R score . Please note.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred) # Evaluation means war between actual and predicted output.
print(cm) # to display the value for cm Evaluation metrics
# the below output overall sum matches the test data count


#To compute the CONFUSION MATRIX in a report format

from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,Y_pred) # war between actual and prediction

# To print the CONFUSION MATRIX in a report format

print(clf_report)

[[42 37]
 [20 21]]
              precision    recall  f1-score   support

           0       0.68      0.53      0.60        79
           1       0.36      0.51      0.42        41

    accuracy                           0.53       120
   macro avg       0.52      0.52      0.51       120
weighted avg       0.57      0.52      0.54       120



C:\Users\krish\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
